apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-68ka
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-tenant/appstudio/devfile-sample-python-basic-68ka@sha256:7ca845bee0ac49a7a9eb103a81a398599326e84eab4f62e8a4202b756cf7d804
        name: my-python
        resources: {}
status: {}
